from fastapi import APIRouter

router = APIRouter()

@router.get('/config/options')
async def get_config_options():
    """Returns dynamic selections for the onboarding/setup form, including city metadata."""
    return {
        'cities': [
            {
                'id': 'bengaluru',
                'name': 'Bengaluru',
                'state': 'Karnataka',
                'lat_min': 12.834, 'lat_max': 13.143,
                'lon_min': 77.460, 'lon_max': 77.780,
                'lat_center': 12.9716, 'lon_center': 77.5946,
                'population': '13.6 Million',
                'area_km2': 741,
                'monitoring_stations': 26,
            },
            {
                'id': 'delhi',
                'name': 'Delhi',
                'state': 'Delhi NCT',
                'lat_min': 28.500, 'lat_max': 28.800,
                'lon_min': 77.000, 'lon_max': 77.300,
                'lat_center': 28.6139, 'lon_center': 77.2090,
                'population': '32.9 Million',
                'area_km2': 1484,
                'monitoring_stations': 40,
            },
            {
                'id': 'mumbai',
                'name': 'Mumbai',
                'state': 'Maharashtra',
                'lat_min': 18.900, 'lat_max': 19.300,
                'lon_min': 72.700, 'lon_max': 73.000,
                'lat_center': 19.0760, 'lon_center': 72.8777,
                'population': '20.7 Million',
                'area_km2': 603,
                'monitoring_stations': 35,
            },
            {
                'id': 'chennai',
                'name': 'Chennai',
                'state': 'Tamil Nadu',
                'lat_min': 12.900, 'lat_max': 13.200,
                'lon_min': 80.150, 'lon_max': 80.300,
                'lat_center': 13.0827, 'lon_center': 80.2707,
                'population': '11.5 Million',
                'area_km2': 426,
                'monitoring_stations': 18,
            },
            {
                'id': 'kolkata',
                'name': 'Kolkata',
                'state': 'West Bengal',
                'lat_min': 22.400, 'lat_max': 22.700,
                'lon_min': 88.300, 'lon_max': 88.450,
                'lat_center': 22.5726, 'lon_center': 88.3639,
                'population': '15.1 Million',
                'area_km2': 205,
                'monitoring_stations': 22,
            },
            {
                'id': 'hyderabad',
                'name': 'Hyderabad',
                'state': 'Telangana',
                'lat_min': 17.300, 'lat_max': 17.600,
                'lon_min': 78.350, 'lon_max': 78.600,
                'lat_center': 17.3850, 'lon_center': 78.4867,
                'population': '10.0 Million',
                'area_km2': 650,
                'monitoring_stations': 14,
            },
            {
                'id': 'ahmedabad',
                'name': 'Ahmedabad',
                'state': 'Gujarat',
                'lat_min': 22.900, 'lat_max': 23.150,
                'lon_min': 72.500, 'lon_max': 72.700,
                'lat_center': 23.0225, 'lon_center': 72.5714,
                'population': '8.4 Million',
                'area_km2': 464,
                'monitoring_stations': 12,
            },
            {
                'id': 'pune',
                'name': 'Pune',
                'state': 'Maharashtra',
                'lat_min': 18.400, 'lat_max': 18.700,
                'lon_min': 73.750, 'lon_max': 74.000,
                'lat_center': 18.5204, 'lon_center': 73.8567,
                'population': '7.4 Million',
                'area_km2': 331,
                'monitoring_stations': 10,
            },
        ],
        'resolutions': [
            {'id': '1km', 'name': '1 km × 1 km', 'description': 'Best hyperlocal accuracy'},
            {'id': '2km', 'name': '2 km × 2 km', 'description': 'Balanced performance'},
            {'id': '5km', 'name': '5 km × 5 km', 'description': 'City-wide overview'},
        ],
        'sources': [
            {
                'id': 'caaqms',
                'name': 'CPCB CAAQMS',
                'description': 'Central Pollution Control Board monitoring stations',
                'status': 'active',
                'last_updated': '5 minutes ago',
            },
            {
                'id': 'weather',
                'name': 'Weather API',
                'description': 'Meteorological parameters — wind, humidity, temperature',
                'status': 'active',
                'last_updated': '1 minute ago',
            },
            {
                'id': 'sentinel5p',
                'name': 'Sentinel-5P Satellite',
                'description': 'ESA satellite — NO₂, SO₂, CO, O₃ column data',
                'status': 'active',
                'last_updated': '3 hours ago',
            },
            {
                'id': 'modis',
                'name': 'MODIS Aerosol',
                'description': 'NASA MODIS Aerosol Optical Depth (AOD)',
                'status': 'active',
                'last_updated': '6 hours ago',
            },
            {
                'id': 'traffic',
                'name': 'Traffic Density',
                'description': 'Vehicle movement and congestion index',
                'status': 'active',
                'last_updated': '2 minutes ago',
            },
        ],
        'horizons': [
            {'id': 'current', 'name': 'Current'},
            {'id': '24h', 'name': '24 Hours'},
            {'id': '48h', 'name': '48 Hours'},
            {'id': '72h', 'name': '72 Hours'},
        ],
    }
